---
label: Product_WhySection
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: type
  label: type
- type: text
  name: description1
  label: description1
- type: text
  name: description2
  label: description2
- type: text
  name: description3
  label: description3
pages:
- content/product/whysection.md
